# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xnobrain/ai/v1/managed_ai.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'xnobrain/ai/v1/managed_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fxnobrain/ai/v1/managed_ai.proto\x12\x0exnobrain.ai.v1\"\x7f\n\x11TranscribeRequest\x12\x1a\n\x08\x66ilename\x18\x01 \x01(\tR\x08\x66ilename\x12\x18\n\x07\x63ontent\x18\x02 \x01(\x0cR\x07\x63ontent\x12\x17\n\x07user_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n\ttenant_id\x18\x04 \x01(\tR\x08tenantId\"(\n\x12TranscribeResponse\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text2g\n\x10ManagedAIService\x12S\n\nTranscribe\x12!.xnobrain.ai.v1.TranscribeRequest\x1a\".xnobrain.ai.v1.TranscribeResponseB\xbb\x01\n\x12\x63om.xnobrain.ai.v1B\x0eManagedAiProtoP\x01Z;github.com/vn-fin/xnobrain/internal/gen/xnobrain/ai/v1;aiv1\xa2\x02\x03XAX\xaa\x02\x0eXnobrain.Ai.V1\xca\x02\x0eXnobrain\\Ai\\V1\xe2\x02\x1aXnobrain\\Ai\\V1\\GPBMetadata\xea\x02\x10Xnobrain::Ai::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xnobrain.ai.v1.managed_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.xnobrain.ai.v1B\016ManagedAiProtoP\001Z;github.com/vn-fin/xnobrain/internal/gen/xnobrain/ai/v1;aiv1\242\002\003XAX\252\002\016Xnobrain.Ai.V1\312\002\016Xnobrain\\Ai\\V1\342\002\032Xnobrain\\Ai\\V1\\GPBMetadata\352\002\020Xnobrain::Ai::V1'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=51
  _globals['_TRANSCRIBEREQUEST']._serialized_end=178
  _globals['_TRANSCRIBERESPONSE']._serialized_start=180
  _globals['_TRANSCRIBERESPONSE']._serialized_end=220
  _globals['_MANAGEDAISERVICE']._serialized_start=222
  _globals['_MANAGEDAISERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
