# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from xnobrain.ai.v1 import managed_ai_pb2 as xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2


class ManagedAIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/xnobrain.ai.v1.ManagedAIService/Transcribe',
                request_serializer=xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class ManagedAIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagedAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeRequest.FromString,
                    response_serializer=xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xnobrain.ai.v1.ManagedAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xnobrain.ai.v1.ManagedAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagedAIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xnobrain.ai.v1.ManagedAIService/Transcribe',
            xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeRequest.SerializeToString,
            xnobrain_dot_ai_dot_v1_dot_managed__ai__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
