"""Private default agent page routes through the existing Runtime facade."""

from ..models.custom_page import (
    ApprovePageSchedule,
    MigratePage,
    PageApproval,
    PageAttachment,
    PageCapabilities,
    PageLifecycle,
    PageRemovalCheck,
    PageRevision,
    PageState,
    PreparePage,
    QueryPage,
    QueryResult,
    RecoverRemoval,
    RemovalRecovery,
    RetainedPages,
    RunPageAction,
    SchedulePage,
    StopPageSchedule,
    WriteRecords,
)
from .definition import route

ROOT = "/agents/{agent_id}/custom-page"
ROUTES = (
    route(
        "GET",
        ROOT + "/removal-recovery",
        "custom_page_removal_recovery",
        tags=("Custom pages",),
        response_data=RemovalRecovery,
    ),
    route(
        "POST",
        ROOT + "/remove-agent/recover",
        "custom_page_recover_removal",
        RecoverRemoval,
        tags=("Custom pages",),
    ),
    route(
        "GET",
        ROOT + "/removal-check",
        "custom_page_removal_check",
        tags=("Custom pages",),
        response_data=PageRemovalCheck,
    ),
    route(
        "GET",
        "/custom-pages/retained",
        "custom_page_retained",
        tags=("Custom pages",),
        response_data=RetainedPages,
    ),
    route(
        "POST",
        ROOT + "/remove-agent",
        "custom_page_remove_agent",
        PageLifecycle,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/schedules/preview",
        "custom_page_schedule_preview",
        SchedulePage,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/schedules",
        "custom_page_schedule_create",
        ApprovePageSchedule,
        tags=("Custom pages",),
    ),
    route("GET", ROOT + "/schedules", "custom_page_schedule_list", tags=("Custom pages",)),
    route(
        "POST",
        ROOT + "/schedules/{schedule_id}/stop",
        "custom_page_schedule_stop",
        StopPageSchedule,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/actions/{action_id}",
        "custom_page_action",
        RunPageAction,
        tags=("Custom pages",),
    ),
    route(
        "GET",
        ROOT + "/revisions/{revision}/migration-plan",
        "custom_page_migration_plan",
        tags=("Custom pages",),
    ),
    route("POST", ROOT + "/migrate", "custom_page_migrate", MigratePage, tags=("Custom pages",)),
    route("GET", ROOT + "/export", "custom_page_export", tags=("Custom pages",)),
    route("POST", ROOT + "/delete", "custom_page_delete", PageLifecycle, tags=("Custom pages",)),
    route(
        "GET",
        ROOT + "/capabilities",
        "custom_page_capabilities",
        tags=("Custom pages",),
        response_data=PageCapabilities,
    ),
    route("GET", ROOT, "custom_page_get", tags=("Custom pages",), response_data=PageState),
    route(
        "POST",
        ROOT + "/drafts",
        "custom_page_prepare",
        PreparePage,
        response_data=PageRevision,
        tags=("Custom pages",),
    ),
    route(
        "GET",
        ROOT + "/revisions/{revision}",
        "custom_page_preview",
        response_data=PageRevision,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/activate",
        "custom_page_activate",
        PageApproval,
        response_data=PageRevision,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/restore",
        "custom_page_restore",
        PageApproval,
        response_data=PageRevision,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/queries/{query_id}",
        "custom_page_query",
        QueryPage,
        response_data=QueryResult,
        tags=("Custom pages",),
    ),
    route(
        "POST",
        ROOT + "/datasets/{dataset_id}/records",
        "custom_page_write",
        WriteRecords,
        tags=("Custom pages",),
    ),
    route("GET", ROOT + "/activity", "custom_page_activity", tags=("Custom pages",)),
    route("POST", ROOT + "/archive", "custom_page_archive", PageLifecycle, tags=("Custom pages",)),
    route("DELETE", ROOT + "/drafts/{revision}", "custom_page_cancel", tags=("Custom pages",)),
    route("POST", ROOT + "/backup", "custom_page_backup", tags=("Custom pages",)),
    route(
        "POST",
        ROOT + "/attachments",
        "custom_page_attachment",
        PageAttachment,
        tags=("Custom pages",),
    ),
    route(
        "GET",
        ROOT + "/attachments/{attachment_id}",
        "custom_page_attachment_read",
        tags=("Custom pages",),
    ),
)
