# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from xnobrain.runtime.v1 import runtime_gateway_pb2 as xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2


class NodeGatewayServiceStub(object):
    """NodeGateway is implemented beside Incus. Control opens one bidirectional
    stream per public Runtime request; the node gateway resolves the private
    address locally and forwards frames to RuntimeGateway over private gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Proxy = channel.stream_stream(
                '/xnobrain.runtime.v1.NodeGatewayService/Proxy',
                request_serializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyRequest.SerializeToString,
                response_deserializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyResponse.FromString,
                _registered_method=True)


class NodeGatewayServiceServicer(object):
    """NodeGateway is implemented beside Incus. Control opens one bidirectional
    stream per public Runtime request; the node gateway resolves the private
    address locally and forwards frames to RuntimeGateway over private gRPC.
    """

    def Proxy(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Proxy': grpc.stream_stream_rpc_method_handler(
                    servicer.Proxy,
                    request_deserializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyRequest.FromString,
                    response_serializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xnobrain.runtime.v1.NodeGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xnobrain.runtime.v1.NodeGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeGatewayService(object):
    """NodeGateway is implemented beside Incus. Control opens one bidirectional
    stream per public Runtime request; the node gateway resolves the private
    address locally and forwards frames to RuntimeGateway over private gRPC.
    """

    @staticmethod
    def Proxy(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xnobrain.runtime.v1.NodeGatewayService/Proxy',
            xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyRequest.SerializeToString,
            xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.NodeGatewayServiceProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RuntimeGatewayServiceStub(object):
    """RuntimeGateway is hosted by the Runtime/Hermes process on a private listener.
    It adapts framed internal requests to the existing FastAPI/Hermes API while
    preserving uploads, binary downloads, SSE, backpressure, and cancellation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Proxy = channel.stream_stream(
                '/xnobrain.runtime.v1.RuntimeGatewayService/Proxy',
                request_serializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyRequest.SerializeToString,
                response_deserializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyResponse.FromString,
                _registered_method=True)


class RuntimeGatewayServiceServicer(object):
    """RuntimeGateway is hosted by the Runtime/Hermes process on a private listener.
    It adapts framed internal requests to the existing FastAPI/Hermes API while
    preserving uploads, binary downloads, SSE, backpressure, and cancellation.
    """

    def Proxy(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Proxy': grpc.stream_stream_rpc_method_handler(
                    servicer.Proxy,
                    request_deserializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyRequest.FromString,
                    response_serializer=xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xnobrain.runtime.v1.RuntimeGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xnobrain.runtime.v1.RuntimeGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeGatewayService(object):
    """RuntimeGateway is hosted by the Runtime/Hermes process on a private listener.
    It adapts framed internal requests to the existing FastAPI/Hermes API while
    preserving uploads, binary downloads, SSE, backpressure, and cancellation.
    """

    @staticmethod
    def Proxy(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xnobrain.runtime.v1.RuntimeGatewayService/Proxy',
            xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyRequest.SerializeToString,
            xnobrain_dot_runtime_dot_v1_dot_runtime__gateway__pb2.RuntimeGatewayServiceProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
