# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from xnobrain.router.v1 import router_pb2 as xnobrain_dot_router_dot_v1_dot_router__pb2


class RouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModels = channel.unary_unary(
                '/xnobrain.router.v1.RouterService/ListModels',
                request_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/xnobrain.router.v1.RouterService/Chat',
                request_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ChatRequest.SerializeToString,
                response_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Responses = channel.stream_stream(
                '/xnobrain.router.v1.RouterService/Responses',
                request_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesRequest.SerializeToString,
                response_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesResponse.FromString,
                _registered_method=True)


class RouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Responses(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsRequest.FromString,
                    response_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsResponse.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ChatRequest.FromString,
                    response_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ChatResponse.SerializeToString,
            ),
            'Responses': grpc.stream_stream_rpc_method_handler(
                    servicer.Responses,
                    request_deserializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesRequest.FromString,
                    response_serializer=xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xnobrain.router.v1.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xnobrain.router.v1.RouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xnobrain.router.v1.RouterService/ListModels',
            xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsRequest.SerializeToString,
            xnobrain_dot_router_dot_v1_dot_router__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xnobrain.router.v1.RouterService/Chat',
            xnobrain_dot_router_dot_v1_dot_router__pb2.ChatRequest.SerializeToString,
            xnobrain_dot_router_dot_v1_dot_router__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Responses(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xnobrain.router.v1.RouterService/Responses',
            xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesRequest.SerializeToString,
            xnobrain_dot_router_dot_v1_dot_router__pb2.ResponsesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
