# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xnobrain/router/v1/router.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'xnobrain/router/v1/router.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fxnobrain/router/v1/router.proto\x12\x12xnobrain.router.v1\"\x13\n\x11ListModelsRequest\"5\n\x12ListModelsResponse\x12\x1f\n\x0bopenai_json\x18\x01 \x01(\x0cR\nopenaiJson\"n\n\x0b\x43hatRequest\x12!\n\x0bopenai_json\x18\x01 \x01(\x0cH\x00R\nopenaiJson\x12\x1f\n\nbody_chunk\x18\x02 \x01(\x0cH\x00R\tbodyChunk\x12\x12\n\x03\x65nd\x18\x03 \x01(\x08H\x00R\x03\x65ndB\x07\n\x05\x66rame\"o\n\x0c\x43hatResponse\x12!\n\x0bopenai_json\x18\x01 \x01(\x0cH\x00R\nopenaiJson\x12\x1f\n\nbody_chunk\x18\x02 \x01(\x0cH\x00R\tbodyChunk\x12\x12\n\x03\x65nd\x18\x03 \x01(\x08H\x00R\x03\x65ndB\x07\n\x05\x66rame\"s\n\x10ResponsesRequest\x12!\n\x0bopenai_json\x18\x01 \x01(\x0cH\x00R\nopenaiJson\x12\x1f\n\nbody_chunk\x18\x02 \x01(\x0cH\x00R\tbodyChunk\x12\x12\n\x03\x65nd\x18\x03 \x01(\x08H\x00R\x03\x65ndB\x07\n\x05\x66rame\"t\n\x11ResponsesResponse\x12!\n\x0bopenai_json\x18\x01 \x01(\x0cH\x00R\nopenaiJson\x12\x1f\n\nbody_chunk\x18\x02 \x01(\x0cH\x00R\tbodyChunk\x12\x12\n\x03\x65nd\x18\x03 \x01(\x08H\x00R\x03\x65ndB\x07\n\x05\x66rame2\x99\x02\n\rRouterService\x12[\n\nListModels\x12%.xnobrain.router.v1.ListModelsRequest\x1a&.xnobrain.router.v1.ListModelsResponse\x12M\n\x04\x43hat\x12\x1f.xnobrain.router.v1.ChatRequest\x1a .xnobrain.router.v1.ChatResponse(\x01\x30\x01\x12\\\n\tResponses\x12$.xnobrain.router.v1.ResponsesRequest\x1a%.xnobrain.router.v1.ResponsesResponse(\x01\x30\x01\x42\xd4\x01\n\x16\x63om.xnobrain.router.v1B\x0bRouterProtoP\x01ZCgithub.com/vn-fin/xnobrain/internal/gen/xnobrain/router/v1;routerv1\xa2\x02\x03XRX\xaa\x02\x12Xnobrain.Router.V1\xca\x02\x12Xnobrain\\Router\\V1\xe2\x02\x1eXnobrain\\Router\\V1\\GPBMetadata\xea\x02\x14Xnobrain::Router::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xnobrain.router.v1.router_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.xnobrain.router.v1B\013RouterProtoP\001ZCgithub.com/vn-fin/xnobrain/internal/gen/xnobrain/router/v1;routerv1\242\002\003XRX\252\002\022Xnobrain.Router.V1\312\002\022Xnobrain\\Router\\V1\342\002\036Xnobrain\\Router\\V1\\GPBMetadata\352\002\024Xnobrain::Router::V1'
  _globals['_LISTMODELSREQUEST']._serialized_start=55
  _globals['_LISTMODELSREQUEST']._serialized_end=74
  _globals['_LISTMODELSRESPONSE']._serialized_start=76
  _globals['_LISTMODELSRESPONSE']._serialized_end=129
  _globals['_CHATREQUEST']._serialized_start=131
  _globals['_CHATREQUEST']._serialized_end=241
  _globals['_CHATRESPONSE']._serialized_start=243
  _globals['_CHATRESPONSE']._serialized_end=354
  _globals['_RESPONSESREQUEST']._serialized_start=356
  _globals['_RESPONSESREQUEST']._serialized_end=471
  _globals['_RESPONSESRESPONSE']._serialized_start=473
  _globals['_RESPONSESRESPONSE']._serialized_end=589
  _globals['_ROUTERSERVICE']._serialized_start=592
  _globals['_ROUTERSERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
